javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/PointerVector.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFCoordinate.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFGeometry.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPoint.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFLineString.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFSurface.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPolygon.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFTriangle.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPolyhedralSurface.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFTriangulatedSurface.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFSolid.java

javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFGeometryCollection.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiPoint.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiLineString.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiPolygon.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiSolid.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFEnvelope.java

javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFTriangulate.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPreparedGeometry.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFCAPI.java
javac -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFAlgorithm.java

java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/PointerVector -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFCoordinate -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFGeometry -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPoint -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFLineString -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFSurface -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPolygon -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFTriangle -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPolyhedralSurface -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFTriangulatedSurface -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFSolid -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFGeometryCollection -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiPoint -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiLineString -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiPolygon -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiSolid -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFEnvelope -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFTriangulate -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPreparedGeometry -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFCAPI -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw
java -jar javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFAlgorithm -Xcompiler -I%BOOST_INCLUDEDIR% -Xcompiler -I%CGAL_INC_DIR% -Xcompiler -I%SFCGAL_INC_DIR% -Xcompiler -I%GMP_INC_DIR% -Xcompiler -I%MPFR_INC_DIR% -Xcompiler -L%BOOST_LIBRARYDIR% -Xcompiler -L%CGAL_LIB_DIR% -Xcompiler -L%SFCGAL_LIB_DIR% -Xcompiler -L%GMP_LIB_DIR% -Xcompiler -L%MPFR_LIB_DIR% -Xcompiler -lboost_system-mgw52-mt-1_55 -Xcompiler -lboost_thread-mgw52-mt-1_55 -Xcompiler -lCGAL -Xcompiler -lCGAL_Core -Xcompiler -lSFCGAL -Xcompiler -lgmp-10 -Xcompiler -lmpfr-4 -properties windows-x86_64-mingw

java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFGeometry

java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFCoordinate
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFGeometry
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPoint
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFLineString
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFSurface
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPolygon
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFTriangle
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPolyhedralSurface
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFTriangulatedSurface
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFSolid

java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFGeometryCollection
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiPoint
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiLineString
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiPolygon
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFMultiSolid
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFEnvelope

java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFTriangulate
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFPreparedGeometry
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFCAPI
java -cp javacpp.jar org/geotools/geometry/iso/sfcgal/wrapper/SFAlgorithm

pause